# Generated by Django 5.1 on 2024-09-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Agri_Shop_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgriElectronicsTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(upload_to="products/agri_electronics_tools/"),
                ),
                ("rating", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="AnimalFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="products/animal_feed/")),
                ("rating", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="FarmEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="products/farm_equipment/")),
                ("rating", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="HighQualitySeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="products/high_quality_seeds/")),
                ("rating", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="OrganicFertilizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="products/organic_fertilizers/")),
                ("rating", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SafePesticide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="products/safe_pesticides/")),
                ("rating", models.FloatField()),
            ],
        ),
    ]
