# Generated by Django 5.1 on 2024-09-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Agri_Shop_App", "0002_agrielectronicstool_animalfeed_farmequipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agrielectronicstool",
            name="rating",
            field=models.TextField(max_length=6),
        ),
        migrations.AlterField(
            model_name="animalfeed",
            name="rating",
            field=models.TextField(max_length=6),
        ),
        migrations.AlterField(
            model_name="farmequipment",
            name="rating",
            field=models.TextField(max_length=6),
        ),
        migrations.AlterField(
            model_name="highqualityseed",
            name="rating",
            field=models.TextField(max_length=6),
        ),
        migrations.AlterField(
            model_name="organicfertilizer",
            name="rating",
            field=models.TextField(max_length=6),
        ),
        migrations.AlterField(
            model_name="safepesticide",
            name="rating",
            field=models.TextField(max_length=6),
        ),
    ]
