# Generated by Django 4.2.15 on 2024-09-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Agri_Shop_App", "0007_remove_contact_info_email_subscribe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
