# Generated by Django 4.2.15 on 2024-09-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Agri_Shop_App", "0008_alter_subscribe_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscribe",
            name="user",
        ),
    ]
